### ISSUE TITLE
indicators: add R018 Single bid received

### ISSUE THREAD

**Issue by yolile** [open-contracting/cardinal-rs#90]
Methodology:

Required OCDS fields: tender/procurementMethod, (tender/numberOfTenderers, OR tender/tenderers/id OR bids/details/tenderers/id)

Calculation method: For tenders  i  where tender/procurementMethod = 'open',

R018i=1  if  tender/numberOfTenderersi=1

**Comment by yolile** [comment]
@jpmckinney comment: _Can alternatively count the length of the array instead of checking for `id`_

**Comment by yolile** [comment]
I guess we could also use `bids/statistics/value` when `bids/statistics/measure = 'bids' `

**Comment by jpmckinney** [comment]
Typically our approach is for the `indicators` command to only look in one place, and for the `prepare` command to fill in that place based on alternative fields. You can log alternatives in https://github.com/open-contracting/cardinal-rs/issues/86

For the first version, I would just use whatever seems like the best (most correct) option for Ecuador.

**Comment by yolile** [comment]
> For the first version, I would just use whatever seems like the best (most correct) option for Ecuador.

Ok so, when `tender/tenderers` is present they always set `tender/numberOfTenderes` but they don't always set bids, so we can use `tender/numberOfTenders`.
