### ISSUE TITLE
R024 and r025 are reported even if the flag wasn't raised.

### ISSUE THREAD

**Issue by georgneu** [open-contracting/cardinal-rs#99]
<img width="987" alt="Screenshot 2024-06-05 at 13 43 59" src="https://github.com/open-contracting/cardinal-rs/assets/8439077/5ed1ac2a-9561-483e-b555-44429b87d4e8">

**Comment by jpmckinney** [comment]
The presence of that metadata seems fine to me?

If you don't want to see them, you can disable them. Or use `--no-meta` to not see any meta at all.

**Comment by yolile** [comment]
Ah, true, we didn't read the documentation about `Meta`
